### ISSUE TITLE
Hi, I have a Encoding Question.

### ISSUE THREAD

**Issue by ericlinAAA** [marcussacana/EushullyEditor#1]
Outputing .bin file with EushullyEditor MUST use shift_jis(Encoding.GetEncoding(932))?
I'd like to change the game script into chinese, but if I save .bin to shift_jis, I'll get garbled. 
Is there any way to fix this?

p.s. I tryied to save script with UTF8 and UTF32, still got garbled.

**Comment by marcussacana** [comment]
Yes, the only way to change the game encoding is modding the engine as well, but it is a pretty complex task.

**Comment by ericlinAAA** [comment]
Thanks for replying! So sad... Don't know how to change the game engine. But there is still some characters in shift_jis that matches chinese, so I can change the terms to overcome that issue.
