### ISSUE TITLE
Hi, question about Main.cs => Import()

### ISSUE THREAD

**Issue by ericlinAAA** [marcussacana/EushullyEditor#2]
When I first save the .bin file, it works perfectly. but if I open the saved file and save another time, next time .bin file that I saved can't be loaded.

I use the Debug mode and see that at Main.cs line 76 => if (StringStart == Script.Length) is true, so the returning string array is empty.
I'd like to know how that works, or is there anything I do wrong, thanks.

my question situation:
1. open origin.bin, and save as test.bin.
2. open test.bin, and save as test2.bin.
3. open test2.bin, and the listBox item can't be showed.

**Comment by marcussacana** [comment]
Try change this propriety to Overwrite: https://github.com/marcussacana/EushullyEditor/blob/3d861e0d6cb2dd88591430aedbe48cb0e13bd995/EushullyEditor/Main.cs#L353

**Comment by ericlinAAA** [comment]
awesome, that works! thanks a lot!
