### ISSUE TITLE
Madou Koukaku config

### ISSUE THREAD

**Issue by Yuletide64** [marcussacana/EushullyEditor#3]
Hi there.

You said to message if there were issues configuring the right game but I wasn't sure how to contact you so here I am. I'm probably out of my depth trying this but I at least wanna give it a go. I would like to try translating Madou Koukaku but I honestly only ever took computer science in first year university so I'm not exactly sure how to configure Eushully editor properly.

Would you be able to give me a rundown on how to do this?

Thanks in advance.

**Comment by marcussacana** [comment]
See an example here: https://github.com/marcussacana/SacanaWrapper/blob/2f115f5fce66b07a06f849589fc8ce8078b3602c/Updater/Rhapsody.cs

The changes usually are about fix the line breaker for each game.
If you game is too updated the tool might not work too without add new opcodes.

**Comment by Yuletide64** [comment]
Ahh awesome that's what you meant. I'll have a bit of a play around with the line breaks if I pop into any problems then.
